.PHONY: all clean

all: pset_4_map pset_4_num pset_4_fs

pset_4_map: pset_4_map.c
	gcc -o pset_4_map -Wall pset_4_map.c

pset_4_num: pset_4_num.c
	gcc -o pset_4_num -Wall pset_4_num.c

pset_4_fs: pset_4_fs.c
	gcc -o pset_4_fs -Wall pset_4_fs.c

clean:
	rm -f *.o pset_4_map pset_4_num pset_4_fs
